DoAn/Controllers/ShoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn.Models;

namespace DoAn.Controllers
{
    public class ShoesController : Controller
    {
        // tạo 1 đối tượng chứa toàn bộ csdl
        DbWebGiayDataContext db = new DbWebGiayDataContext();

        private List<Product> LayGiayMoi(int count)
        {
            //sx giảm dần theo ngày update_at
            return db.Products.OrderByDescending(a => a.Update_at).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var giaymoi = db.Products.OrderBy(a => a.Update_at).ToList();
            //lấy giày mới nhất
            //var giayMoi = LayGiayMoi();
            return View(giaymoi);
        }

        public List<Product> ListFusal (int id = 1)
        {
            return db.Products.OrderByDescending(a => a.ID_Cat == id).Take(id).ToList();
        }
        //[ValidateInput(false)]
        public ActionResult listF()
        {
            var list = ListFusal(100);
            return View(list);
        }


        // giày theo loại
        public ActionResult LoaiGiay()
        {
            var LoaiGiay = from lg in db.Categories select lg;
            return PartialView(LoaiGiay);
        }
        public ActionResult giayTheoLoai(int id)
        {
            var giay = from s in db.Products where s.ID_Cat == id select s;
            return View(giay);
        }


        // giày theo NSX
        public ActionResult NhaSX()
        {
            var Nsx = from nsx in db.NSXes select nsx;
            return PartialView(Nsx);
        }
        public ActionResult giayTheoNSX(int id)
        {
            var giay = from s in db.Products where s.ID_NSX == id select s;
            return View(giay);
        }

        public ActionResult Detail(int id)
        {
            //var giay = from s in db.Products
            //           where s.ID_Product == id
            //           select s;

            var giay = db.Products.FirstOrDefault(m => m.ID_Product == id);
            return View(giay);
        }
    }
}

DoAn/Controllers/UserController.cs
using DoAn.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoAn.Controllers
{
    public class UserController : Controller
    {
        DbWebGiayDataContext db = new DbWebGiayDataContext();
        // GET: User

        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            //gán giá trị cho biến người dùng nhập
            var Username = collection["Username"];
            var Password = collection["Password"];
            if (String.IsNullOrEmpty(Username))
            {
                ViewData["Loi1"] = "Nhập tên";
            }
            else if (String.IsNullOrEmpty(Password))
            {
                ViewData["Loi2"] = "Nhập mật khẩu";
            }
            else
            {
                //gán đối tượng cho đối tượng tạo mới
                User user = db.Users.SingleOrDefault(n => n.UserName == Username && n.Password == Password);
                if (user != null)
                {
                    ViewBag.ThongBao = " Đăng nhập thành công";
                }
                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }


        [HttpGet]
        public ActionResult DangKi()
        {
            return View();
        }

        //POST: hàm đăng ký
        [HttpPost]
        public ActionResult DangKi(FormCollection collection, User user)
        {
            var Username = collection["HoTenKh"];
            var Email = collection["Email"];
            var PhoneNumber = collection["PhoneNumber"];
            var Address = collection["Address"];
            var Password = collection["Password"];

            if (String.IsNullOrEmpty(Username))
            {
                ViewData["Loi1"] = "Họ tên không được để trống";
            }
            else if (String.IsNullOrEmpty(Email))
            {
                ViewData["Loi2"] = "Email không được để trống";
            }
            else if (String.IsNullOrEmpty(PhoneNumber))
            {
                ViewData["Loi3"] = "số điện thoại không được để trống";
            }
            else if (String.IsNullOrEmpty(Address))
            {
                ViewData["Loi4"] = "Địa chỉ không được để trống";
            }
            if (String.IsNullOrEmpty(Password))
            {
                ViewData["Loi5"] = "Mật khẩu không được để trống";
            }
            else
            {
                //gán giá trị mới cho đối tượng được tạo mới
                user.UserName = Username;
                user.Email = Email;
                user.Phone = PhoneNumber;
                user.Address = Address;
                user.Password = Password;
                db.Users.InsertOnSubmit(user);
                db.SubmitChanges();
                return RedirectToAction("Login");
            }
            return this.DangKi();
        }
    }
}

DoAn/Views/Shared/Footer.cshtml
<link href="~/css/Footer.css" rel="stylesheet" />
<!-- footer section -->
<footer class="footer_section">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-col">
                <div class="footer_contact">
                    <h4>
                        Contact
                    </h4>
                    <div class="contact_link_box">
                        <a href="https://bitly.com.vn/tdue0o" target="_blank">
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            <spaGoogle Map
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <span>
                                Hotline: 0123456789
                            </span>
                        </a>
                        <a href="">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>
                                meme@gmail.com
                            </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-col">
                <div class="footer_detail">
                    <a href="" class="footer-logo">
                        Fanatics
                    </a>
                    <div class="footer_social">
                        <a href="">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                        <a href="">
                            <i class="fa fa-pinterest" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 footer-col">
                <h4>
                    Open
                </h4>
                <p>
                    To Monday - Saturday
                </p>
                <p>
                    10.00 Am -10.00 Pm
                </p>
            </div>
        </div>
        <div class="footer-info">
            <p>
                &copy; <span id="displayYear"></span>
            </p>
        </div>
    </div>
</footer>
<!-- footer section -->

DoAn/Views/Shared/Header.cshtml
<div class="header">
    <div class="container">
        <!--logo & menu-->
        <div style="color:yellow" class="navbar navbar-fixed-top" >
            <!--logo-->
            <div class="logo">
                <img src="~/img/logo-one.png" width="125px">
            </div>
            <!--menu-->
            <nav>
                <ul id="MenuItems">
                    <li> <a href="@Url.Action("Index","Shoes")">Home</a></li>
                    <li> <a href="">About</a></li>
                    <li> <a href="">Contact</a></li>
                </ul>
                <div class="dropdown">
                    <a class="dropbtn">Product</a>
                    <div class="dropdown-content">
                        @Html.Action("LoaiGiay", "Shoes")
                    </div>
                </div>
                <div class="dropdown">
                    <a class="dropbtn">Nhà Sản Xuất</a>
                    <div class="dropdown-content">
                       @Html.Action("NhaSX","Shoes")
                    </div>
                </div>
                <div class="dropdown">
                    <a class="dropbtn">Account</a>
                    <div class="dropdown-content">
                        <a href="@Url.Action("DangKi","User")">Đăng Kí</a>
                        <a href="@Url.Action("Login","User")">Đăng Nhập</a>
                    </div>
                </div>
            </nav>
            <!--icon cart-->
            <a href="@Url.Action("GioHang","GioHang")">
                <img src="~/img/cart.png" width="25px" height="25px">
            </a>
            
        </div>
        <!-- End logo and menu -->
        <!-- banner -->
        <div class="row">
            <!-- cột phần chữ -->
            <div class="col-2">
                <h1>Đã chơi là phải CHẤT</h1>
                <p>
                    Với nhiều mẫu mã đẹp phong phú và đa dạng về kiểu dáng và màu sắc,
                    <br> bạn dễ dàng lựa chọn cho bản thân một đôi giày ưng ý.
                </p>
                <!--<a href="" class="btn">Explore now &#10132;</a>-->
            </div>
            <!-- cột phần hình ảnh -->
            <div class="col-2">
                <img src="~/img/all-sports-banner.png">
            </div>
        </div>
        <!-- end banner -->
    </div>
</div>

DoAn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DoAn/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/Dan.css">
    <script src="~/tinymce_6.1.0/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ Selection: 'textarea' });</script>
</head>
<body>
    <div class="header">
        <div class="container">
            <!--logo & menu-->
            <div style="color:yellow" class="navbar navbar-fixed-top">
                <!--logo-->
                <div class="logo">
                    <img src="~/img/logo-one.png" width="125px">
                </div>
                <!--menu-->
                <nav>
                    <ul id="MenuItems">
                        <li>
                            @Html.ActionLink("TRANG CHỦ", "Index", "Admin")
                        </li>
                    </ul>
                    <div class="dropdown">
                        <li>
                            @Html.ActionLink("QUẢN LÍ CHỦ ĐỀ", "Product", "Admin")
                        </li>
                    </div>
                    <div class="dropdown">
                        <li>
                            @Html.ActionLink("QUẢN LÍ NHÀ SẢN XUẤT", "NhaSX", "Admin")
                        </li>
                    </div>
                    
                </nav>
                
                <!--icon cart-->
                <a href="@Url.Action("GioHang","GioHang")">
                    <img src="~/img/cart.png" width="25px" height="25px">
                </a>

            </div>
            <!-- End logo and menu -->
            <!-- banner -->
            <div class="row">
                <!-- cột phần chữ -->
                <div class="col-2">
                    <h1>Đã chơi là phải CHẤT</h1>
                    <p>
                        Với nhiều mẫu mã đẹp phong phú và đa dạng về kiểu dáng và màu sắc,
                        <br> bạn dễ dàng lựa chọn cho bản thân một đôi giày ưng ý.
                    </p>
                    <!--<a href="" class="btn">Explore now &#10132;</a>-->
                </div>
                <!-- cột phần hình ảnh -->
                <div class="col-2">
                    <img src="~/img/all-sports-banner.png">
                </div>
            </div>
            <!-- end banner -->
        </div>
    </div>

    @*<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li>
                @Html.ActionLink("TRANG CHỦ", "Index", "Admin")
            </li>
            <li>
                @Html.ActionLink("QUẢN LÍ CHỦ ĐỀ", "Product", "Admin")
            </li>
            <li>
                @Html.ActionLink("QUẢN LÍ NHÀ SẢN XUẤT", "NhaSX", "Admin")
            </li>

        </ul>
    </div>*@
    <div>
        @RenderBody()
    </div>
    @Html.Partial("Footer");

</body>
</html>

DoAn/Views/Shared/_LayoutMoi.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/LTW.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <title>Website Bán Xe - AroundTheClock</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color: whitesmoke">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AroundTheClock", "Index", "CarStore", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giới Thiệu", "About", "CarStore")</li>
                    <li>@Html.ActionLink("Liên Hệ", "Contact", "CarStore")</li>
                    <li>@Html.ActionLink("Tin Tức", "Index", "TinTuc")</li>
                    <li>@Html.ActionLink("Sản Phẩm", "Sanpham", "CarStore")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.Action("GioHangPartial", "GioHang")</li>
                    <li>@Html.ActionLink("Đăng Nhập", "Dangnhap", "KhachHang")</li>
                    <li>@Html.ActionLink("Đăng Ký", "Dangky", "KhachHang")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <br />
                <p class="lead">Product</p>
                @Html.Action("giayTheoLoai", "Shoes")
                <br />
                <p class="lead">Nhà sản xuất</p>
                @Html.Action("Hangxe", "CarStore")
            </div>
            <div class="col-md-9">
                @*Slide chuyển hình*@
                <div class="row carousel-holder">
                    <div class="col-md-12">
                        <br />
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img class="slide-image" src="~/Content/images/banner1.jpg" alt="">

                                </div>
                                <div class="item">
                                    <img class="slide-image" src="~/Content/images/banner2.jpg" alt="">

                                </div>
                                <div class="item">
                                    <img class="slide-image" src="~/Content/images/banner3.jpg" alt="">

                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div>
                    @RenderBody()
                </div>

            </div>
        </div>
    </div>



    <div class="container body-content">
        <hr />
        <footer>

            <p>&copy; @DateTime.Now.Year - ASP.NET Application - Nhóm 2</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>

DoAn/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("Header");
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/Dan.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    
    <div>
        @RenderBody()
    </div>

    <!-- Footer -->
    @Html.Partial("Footer");

</body>
</html>